# ⚠️  Replace 100.x.x.x with your actual Tailscale IPs!
#     Find the IP inside each VM with: tailscale ip -4

[wazuh_manager]
wazuh-manager ansible_host=192.168.56.10

[web_servers]
web-agent ansible_host=192.168.56.11

[db_servers]
db-agent ansible_host=192.168.56.12

# Group for base installation
[wazuh_agents:children]
web_servers
db_servers

[all:vars]
ansible_user=vagrant
# Dynamic path to the private key for each VM
ansible_ssh_private_key_file=../.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key
ansible_ssh_common_args='-o StrictHostKeyChecking=no'