---
- name: Add Wazuh GPG key
  apt_key:
    url: https://packages.wazuh.com/key/GPG-KEY-WAZUH
    state: present

- name: Add Wazuh apt repository
  apt_repository:
    repo: "deb https://packages.wazuh.com/4.x/apt/ stable main"
    filename: wazuh
    state: present

- name: Ensure ossec group exists
  group:
    name: ossec
    state: present

- name: Install wazuh-agent
  apt:
    name: wazuh-agent
    update_cache: yes
    state: present
  environment:
    WAZUH_MANAGER: "{{ wazuh_manager_ip }}"
    WAZUH_AGENT_NAME: "{{ wazuh_agent_name }}"

- name: Reload systemd after wazuh-agent install
  systemd:
    daemon_reload: yes

- name: Enable and start wazuh-agent
  systemd:
    name: wazuh-agent
    enabled: yes
    state: started
    daemon_reload: yes

- name: Configure agent to monitor auth.log
  blockinfile:
    path: /var/ossec/etc/ossec.conf
    insertafter: "<ossec_config>"
    block: |
      <localfile>
        <log_format>syslog</log_format>
        <location>/var/log/auth.log</location>
      </localfile>
  notify: restart wazuh-agent

- name: Restart wazuh-agent to apply changes
  systemd:
    name: wazuh-agent
    state: restarted
